### ISSUE TITLE
Circle past niet in mobile

### ISSUE THREAD

**Issue by KoopReynders** [rosahoffer/avocado-media-vacature-detailpagina#3]
https://github.com/rosahoffer/the-startup-responsive-interactieve-website/blob/feb0f21744163afd95af498bc955895a496b8d49/style.css#L75-L83

De circle heeft pixels voor de breedte en hoogte, daarom past die niet in een S scherm. 
Dit kun je oplossen met een `overflow-x` op het parent element. 
https://css-tricks.com/almanac/properties/o/overflow/

**Comment by rosahoffer** [comment]
gelukt!
