### ISSUE TITLE
Dit is navigatie, nam gebruiken?

### ISSUE THREAD

**Issue by KoopReynders** [rosahoffer/avocado-media-vacature-detailpagina#6]
https://github.com/rosahoffer/the-startup-responsive-interactieve-website/blob/feb0f21744163afd95af498bc955895a496b8d49/vac-frontender.html#L43-L45

Je mag in een pagina meerdere `nav` elementen gebruiken. 
(voor zover ik weet)
correct me if i'm wrong !

**Comment by rosahoffer** [comment]
p veranderd in nav, thanks!
